// js-solid/src/index.tsx
/* @refresh reload */
import 'virtual:uno.css'
import '@unocss/reset/normalize.css'
import 'xml-viewer-component/dist/esm/xmlviewercomponent'
import { render } from 'solid-js/web';

import App from './App';

const root = document.getElementById('root');

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    'Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?',
  );
}

render(() => <App />, root!);

// js/src/index.tsx
/* @refresh reload */
import "virtual:uno.css";
import "@unocss/reset/normalize.css";
import { createRoot } from "react-dom/client";

import App from "./App";

const root = document.getElementById("root");

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    "Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?",
  );
}
createRoot(root!).render(<App />);
